spring.application.name=National-Countries-System
server.port=8081

countries.external.api.url=${COUNTRIES_EXTERNAL_API_URL}
api.key=${API_KEY}
country.data.external.api.url=${COUNTRY_DATA_EXTERNAL_API_URL}
weather.api.url=${WEATHER_API_URL}

spring.cache.type=${SPRING_CACHE_TYPE}
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.cache.redis.time-to-live=${SPRING_CACHE_REDIS_TIME_TO_LIVE}

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
