spring.application.name=National-Countries-System
server.port=8081


countries.external.api.url=https://countriesnow.space/api/v0.1/countries
api.key=8G8ii2K8okXT0Fbw1vMIwA==wswrBR17Nz8coIO1
country.data.external.api.url=https://api.api-ninjas.com/v1/country?name=
weather.api.url=https://api.api-ninjas.com/v1/weather?city=


spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.redis.time-to-live=20000


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest